import Link from 'next/link'
import {getPublications} from '@/lib/sanity'

export default async function Home(){
  const pubs = await getPublications()
  const latest = pubs[0]
  return <main>
    <section className="hero shell">
      <div className="hero-title"><p className="eyebrow"><span aria-hidden="true"></span>Independent research for Africa’s climate economy</p><h1>Evidence for Africa’s transition, <em>and the people living it.</em></h1></div>
      <div className="hero-copy"><p className="standfirst">StoneComms is an independent research and intelligence firm examining the systems shaping Africa’s climate economy—from electrification and industrialisation to the people and institutions making the transition real.</p><p>We combine public evidence, original enquiry and lived experience to produce clear, decision-useful intelligence for investors, institutions and leaders—and work the public can interrogate.</p><div className="actions"><Link className="button dark" href="/research">Read the research <span>↓</span></Link><Link className="text-link" href="/#commission">Commission a project ↗</Link></div></div>
    </section>

    <section className="signal"><div className="shell signal-grid"><div className="signal-label"><p className="eyebrow"><span aria-hidden="true"></span>Our field of view</p></div><div className="blocks" aria-label="Africa, Energy, Industry and Voice are StoneComms fields of view"><div>Africa</div><div>Energy</div><div>Industry</div><div className="ochre">Voice</div></div><p className="signal-note">Capital · infrastructure · adoption · voice</p></div></section>

    <section id="research" className="section shell research"><div className="section-intro"><p className="eyebrow"><span aria-hidden="true"></span>Research agenda · 2026</p><h2>Three questions guide our work.</h2><p>Where is change happening? Who benefits? Who has been heard in deciding what happens next?</p></div><div className="research-cards"><article><span className="number">01</span><h3>Electric mobility</h3><p>Tracking the commercial models, infrastructure and public policy shaping Africa’s transition to electric transport.</p></article><article><span className="number">02</span><h3>Industrial transition</h3><p>Following the capital, manufacturing choices and local value chains behind the continent’s climate economy.</p></article><article><span className="number">03</span><h3>Voice and legitimacy</h3><p>Examining whose experience reaches decision-makers—and what gets missed when it does not.</p></article></div><div className="repository-link"><Link href="/research">Browse the research repository ↗</Link></div></section>

    <section className="value"><div className="shell value-grid"><p className="eyebrow"><span aria-hidden="true"></span>The value of research</p><div><h2>Better evidence changes what organisations see—and what they do next.</h2><p>It reduces uncertainty before capital is committed, exposes risk before it becomes costly and tests whether strategy matches conditions on the ground.</p></div></div></section>

    <section className="section shell programme"><p className="eyebrow"><span aria-hidden="true"></span>Latest from the research repository</p>{latest ? <div className="programme-grid"><div className="programme-main"><h2>{latest.title}</h2>{latest.pdfUrl ? <Link className="pdf-download" href={latest.pdfUrl}>Download PDF ↓</Link> : null}{latest.standfirst && <p className="lead">{latest.standfirst}</p>}<Link className="programme-read" href={`/research/${latest.slug}`}>Read the publication ↗</Link></div><aside><p className="eyebrow"><span aria-hidden="true"></span>{latest.publicationType?.replaceAll('-', ' ') || 'Research'}</p><div className="field-code"><strong>{latest.publicationDate || 'Latest'}</strong><span>{latest.byline || 'StoneComms Research & Intelligence'}</span></div><p>This preview is drawn automatically from the newest publication in the repository.</p><Link href="/research">Browse all research ↗</Link></aside></div> : <div className="programme-main"><h2>Research is being prepared for publication.</h2><Link className="programme-read" href="/research">Browse the research repository ↗</Link></div>}</section>

    <section id="method" className="method"><div className="shell"><div className="method-head"><p className="eyebrow"><span aria-hidden="true"></span>The StoneComms evidence standard</p><h2>Useful intelligence should show its workings.</h2></div><div className="principles"><article><span>Principle 01</span><h3>Source first</h3><p>Claims begin with primary documents, public data and attributable evidence.</p></article><article><span>Principle 02</span><h3>Limits visible</h3><p>Uncertainty, incomplete data and competing interpretations remain part of the published record.</p></article><article><span>Principle 03</span><h3>People count</h3><p>Investment and policy are tested against the experience of those expected to live with them.</p></article><article><span>Principle 04</span><h3>Human first</h3><p>AI supports discovery and analysis. Lee Breheny remains editor and accountable author.</p></article></div></div></section>

    <section id="commission" className="section shell commission"><div className="commission-title"><p className="eyebrow"><span aria-hidden="true"></span>Commission StoneComms</p><h2>When the public record is not enough, <em>we find what is missing.</em></h2></div><div className="commission-copy"><p className="lead">Commissioned market intelligence, stakeholder research, evidence-led thought leadership and executive briefings for organisations financing, building and governing Africa’s climate economy.</p><ul><li>Market and policy research</li><li>Stakeholder and lived-experience studies</li><li>Research-led narrative and thought leadership</li><li>Executive and investment briefings</li></ul><a className="button teal" href="mailto:lee@stonecomms.com?subject=Commissioning%20StoneComms">Discuss a project <span>↗</span></a></div></section>

    <section id="about" className="about"><div className="shell about-grid"><div><p className="eyebrow"><span aria-hidden="true"></span>Editor and Research Director</p><div className="portrait-mark" aria-hidden="true"><span>LB</span><small>/ 01</small></div></div><div><h2>Lee Breheny</h2><p className="about-standfirst">From newsroom to boardroom, with the evidence kept in view.</p><p>Lee served as Chief Communications Officer for Equitane, a multi-billion-dollar African industrialisation and investment platform, after helping build the public narrative of African electric-mobility company Spiro. A former BBC editorial leader and communications executive, his research at Oxford Brookes examines voice, marginalisation and editorial inclusion in UK journalism.</p><a className="email" href="mailto:lee@stonecomms.com">lee@stonecomms.com ↗</a></div></div></section>
  </main>
}
